import Header from "@/components/header";
import "../styles/global.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer";
import StoreProvider from "@/stores/store-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="tr">
			<body className={`${inter.className} flex flex-col`}>
				<StoreProvider>
					<Header />
					<main className="mt-10">{children}</main>
					<Footer />
				</StoreProvider>
			</body>
		</html>
	);
}
